### ISSUE TITLE
Disabling the message "N results are available, use up and down arrow keys to navigate."

### ISSUE THREAD

**Issue by smakthe** [bigtunacan/rails-jquery-autocomplete#89]
Hello Joiey,
I used your gem. It did my job pretty well. Thank you!
However, it is leaving a message like "2 results are available, use up and down arrow keys to navigate." below the webpage footer. I want to stop that. Help me with this issue.
Thanks and regards,
Somak

**Comment by jd1386** [comment]
In your CSS file, add the following:
```css
.ui-helper-hidden-accessible {
  display: none !important;
}
```
This works for me!
